name: information_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.0
  cloud_firestore: ^4.7.1
  file_picker: ^5.3.2
  just_audio: ^0.9.34
  audio_session: ^0.1.16
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
